title: "Vaguely Generic"
tagline: "An online presence about nothing specific."
description: "Vaguely Generic is a presence that exists to do whatever."
baseurl: ""
url: "https://vaguelygeneric.website"
email: "email@vaguelygeneric.website"
# YouTube
youtube_channel: "https://www.youtube.com/@VaguelyGeneric"

# Collections
collections:
  shows:
    output: true
    permalink: /podcast/:slug/
  podcast:
    output: true
    permalink: /podcast/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  guests:
    output: true
    permalink: /guests/:slug/

defaults:
  - scope:
      path: ""
      type: "shows"
    values:
      layout: "show"
  - scope:
      path: ""
      type: "podcast"
    values:
      layout: "episode"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "guests"
    values:
      layout: "guest"

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:categories/:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - Dockerfile
  - tools
  - temp